# docker-compose.yml
version: '3'
services:
  app:
    build: .
    container_name: app
    volumes:
      - .:/var/www
    networks:
      - app_network
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: secret
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
