version: '3.8'

services:
  # PHP + Apache container
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=laravel
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  # PostgreSQL container
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

  # Redis container (optional for caching, queues)
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - app-network
    ports:
      - "6379:6379"

# Volumes for persistent data
volumes:
  postgres_data:

# Define the network
networks:
  app-network:
    driver: bridge
